module.exports = {
    applePodcasts: 'Apple Podcasts',
    codepen: 'CodePen',
    discord: 'Discord',
    facebook: 'Facebook',
    github: 'GitHub',
    googlePodcasts: 'Google Podcasts',
    gumroad: 'Gumroad',
    indieHackers: 'Indie Hackers',
    instagram: 'Instagram',
    linkedin: 'LinkedIn',
    npm: 'npm',
    productHunt: 'Product Hunt',
    slack: 'Slack',
    spotify: 'Spotify',
    twitch: 'Twitch',
    twitter: 'Twitter',
    website: 'Website',
    youtube: 'YouTube',
}
