export type Category =
    | 'Accessibility'
    | 'AI'
    | 'Analytics'
    | 'Animation'
    | 'API Building'
    | 'Audio'
    | 'Authentication'
    | 'Blockchain'
    | 'Blog'
    | 'Book'
    | 'Browser'
    | 'CDN'
    | 'CMS'
    | 'Cheatsheet'
    | 'Cloud Computing'
    | 'Code Challenge'
    | 'Code Generator'
    | 'Code Snippet'
    | 'Color'
    | 'Conference'
    | 'Database'
    | 'Design'
    | 'Documentation'
    | 'Domain'
    | 'Editor'
    | 'Email'
    | 'Extension'
    | 'Font'
    | 'Forum'
    | 'Freelance'
    | 'Hacktoberfest'
    | 'Hosting'
    | 'Icon'
    | 'Illustration'
    | 'Image'
    | 'Inspiration'
    | 'Interview'
    | 'Job'
    | 'Learn'
    | 'Legal'
    | 'Logging'
    | 'Logo'
    | 'Library'
    | 'Marketing'
    | 'Newsletter'
    | 'Open Source'
    | 'Performance'
    | 'Personal Website'
    | 'Podcast'
    | 'Productivity'
    | 'Programming'
    | 'Prototyping'
    | 'Remote'
    | 'Resume'
    | 'Scraping'
    | 'Screenshot'
    | 'Security'
    | 'SEO'
    | 'Serverless'
    | 'Social Media'
    | 'Storage'
    | 'Startup'
    | 'Template'
    | 'Terminal'
    | 'Testing'
    | 'Tooling'
    | 'Typing'
    | 'UI'
    | 'UX'
    | 'Video'
    | 'Web3'
    | 'Website Builder'
    | 'Writing'
    | 'YouTube Channel'
