module.exports = [
    {
        name: 'iconmonstr',
        description: 'Free simple icons for your next project.',
        url: 'https://iconmonstr.com',
        icon: 'https://cdns.iconmonstr.com/wp-content/themes/iconmonstr/assets/ico/2.0.0/favicon.ico',
    },
    {
        name: 'Icons8',
        description:
            'Beautiful library of royalty free images and stock photos for personal and commercial use. Download the most consistent set of photography and backgrounds.',
        url: 'https://photos.icons8.com/',
        icon: 'https://photos.icons8.com/vue-static/moose/favs/favicon.ico',
    },
    {
        name: 'Icons8',
        description:
            'Explore a beautiful library of royalty free illustrations, vector images and clipart graphics. Download illustration images  in PNG and SVG formats for free.',
        url: 'https://icons8.com/illustrations',
        icon: 'https://icons8.com/vue-static/ouch/seo/favicon.png',
    },
    {
        name: 'Icons8',
        description:
            '⬇️ Get free icons for graphic design, UI, social media, and mobile. Search for static and animated icons with consistent quality. PNG, SVG, GIF, AE formats.',
        url: 'https://icons8.com/icons',
        icon: 'https://icons8.com/vue-static/icon/favicon/favicon_16.png',
    },
    {
        name: 'Iconscout',
        description:
            'Pixel-perfect vector icons and Icon Fonts available in Line, Monochrome, and Solid style for your next project.',
        url: 'https://iconscout.com/unicons',
        icon: 'https://iconscout.com/favicon-96x96.png',
    },
    {
        name: 'Iconshock',
        description:
            'Free icons and premium icon packs.  Flat icons, Material icons, Glyph icons, iOS icons, Font icons, and more design styles. Vector files, including PNG and SVG icons. Ready for apps, web or social media projects.',
        keywords: [
            'web icons',
            'web icon set',
            'web icon',
            'professional icons',
            'software  web icons',
            'web icons vista',
            'xp web icons',
            'windows vista icons',
            'windows icons',
            'vector icons',
            'vector web icons',
            'application icons',
            'java web icons',
            'video icons',
            'business icons',
            'multimedia icons',
            'accounting icons',
            'web icon packs',
            'web icone',
        ],
        url: 'https://www.iconshock.com/',
        icon: 'https://www.iconshock.com/img/favicon.ico',
    },
    {
        name: 'IconSweets',
        url: 'https://www.designbombs.com/iconsweets2/',
        icon: 'https://www.designbombs.com/iconsweets2/favicon-96x96.png',
    },
    {
        name: 'Icônes',
        url: 'https://icones.netlify.app/',
        icon: 'https://icones.netlify.app/favicon.svg',
    },
    {
        name: 'Image Optimizer',
        url: 'http://www.imageoptimizer.net/Pages/Home.aspx',
        icon: 'data:image/x-icon;,',
    },
    {
        name: 'Inclusive Components',
        description:
            'A blog trying to be a pattern library. All about designing inclusive web interfaces, piece by piece.',
        url: 'https://inclusive-components.design/',
        icon: 'https://inclusive-components.design/favicon.ico',
    },
    {
        name: 'Indeed',
        description: 'Build and upload your resume to Indeed and let your next job find you.',
        url: 'https://www.indeed.com/create-resume',
        icon: 'https://www.indeed.com/profile/gatsby-assets/icons/icon-96x96.png?v=d69338e3b43810840b9a84d69dbaa30e',
    },
    {
        name: 'Indie Drops',
        description: 'Secure unbelivably good deals on early-stage products before they take off.',
        url: 'http://indiedrops.com/',
        icon: 'http://indiedrops.com/apple-touch-icon.png',
    },
    {
        name: 'Indie Hackers',
        description: 'Get the latest tactics, opportunities, and stories from the best podcasts in the industry.',
        url: 'https://www.indiehackers.com/podcast',
        icon: 'https://www.indiehackers.com/images/favicons/favicon--32x32.png',
    },
    {
        name: 'Indie Hackers',
        description:
            'Connect with developers who are sharing the strategies and revenue numbers behind their companies and side projects.',
        url: 'https://www.indiehackers.com/',
        icon: 'https://www.indiehackers.com/images/favicons/favicon--32x32.png',
    },
    {
        name: 'Inovatik',
        description:
            'HTML templates designed to power up your online projects with responsive layout, included reusable images and simple licensing.',
        url: 'https://inovatik.com/',
        icon: 'https://inovatik.com/images/favicon.png',
    },
    {
        name: 'Insomnia',
        description: 'Design & Debug APIs like a human, not a robot.',
        url: 'https://insomnia.rest/',
        icon: 'https://insomnia.rest/icons/icon-96x96.png?v=b68a1a35ee1565b759a2d4edb26074be',
    },
    {
        name: 'IntelliJ IDEA',
        description: 'A Capable and Ergonomic Java IDE for Enterprise Java, Scala, Kotlin and much more...',
        url: 'https://www.jetbrains.com/idea/',
        icon: 'https://www.jetbrains.com/favicon-32x32.png',
    },
    {
        name: 'Interfacer',
        description: 'Interfacer is a collection of 300+ free design resources found on the Web.',
        keywords: [
            'design resources',
            'web design',
            'freedesignresources',
            'free design resources',
            'fonts',
            'free illustration',
            'freebies',
            'freebie illustration',
            'UI kits',
            'design kit',
            'Illustrations',
            'free fonts',
            'free Illustrations',
            'free mockups',
            'free icons',
            'Interfacer',
            'Interfacer list',
            'Interfacer design resource',
            'Interfacer resources',
            'Interfacer design resources',
        ],
        url: 'https://interfacer.xyz/',
        icon: 'https://interfacer.xyz/assets/site_assets/interfacelogo-icon.png',
    },
    {
        name: 'iOS Dev Jobs',
        description:
            'Browse the very best iOS development jobs available, or sign up and get a weekly digest delivered by email every Monday.',
        url: 'https://iosdevjobs.com/',
        icon: 'https://iosdevjobs.com/wp-content/uploads/2019/01/cropped-favicon-32x32.png',
    },
    {
        name: 'IRA Design',
        description: 'Open-source illustrations that fits perfectly for any project you desire.',
        keywords: [
            'illustration',
            'app',
            'website illustration',
            'app illustration',
            'design component',
            'custom illustration',
            'illustration component',
            'color gradient',
            'gradients',
            'gallery',
            'best illustrations',
            'colorful illustrations',
        ],
        url: 'https://iradesign.io/gallery/illustrations',
        icon: 'https://iradesign.io/assets/img/favicon.png',
    },
    {
        name: 'Isometriclove',
        url: 'https://isometriclove.com/',
        icon: 'https://isometriclove.com/favicon.ico',
    },
]
