import { categories } from 'const'
import { Resource } from 'types'

const { assets, toolsAndUtilities, jobs, indieHacking, programming } = categories

export const resources: Resource[] = [
    {
        name: 'Icon Horse',
        categories: [assets.icons],
        description:
            'Free, easy to use, highest resolution possible favicons for any web site – including fallbacks if none are found.',
        keywords: ['favicons', 'logo icons', 'web icons', 'logos', 'site logos'],
        url: 'https://icon.horse',
        icon: 'https://icon.horse/icon/icon.horse',
    },
    {
        name: 'Iconfinder',
        categories: [assets.icons, assets.illustrations],
        description: 'Millions of graphics for your design projects. Created by independent designers.',
        url: 'https://www.iconfinder.com',
        icon: 'https://www.iconfinder.com/static/img/favicons/favicon-32x32.png?87b2a5c3aa',
        keywords: [],
    },
    {
        name: 'Iconic',
        categories: [assets.icons],
        description: 'Free, “do wtf you want with” pixel-perfect icons. New icons added every week',
        url: 'https://iconic.app',
        icon: 'https://iconic.app/wp-content/themes/basis-iconic/icon.png',
    },
    {
        name: 'iconmonstr',
        categories: [assets.icons],
        description: 'Free simple icons for your next project.',
        url: 'https://iconmonstr.com',
        icon: 'https://cdns.iconmonstr.com/wp-content/themes/iconmonstr/assets/ico/2.0.0/favicon.ico',
    },
    {
        name: 'Icons8',
        categories: [assets.icons, assets.illustrations, assets.images, assets.audio],
        description:
            'Download design elements for free: icons, photos, vector illustrations, and music for your videos.',
        url: 'https://icons8.com',
        icon: 'https://logos-download.com/wp-content/uploads/2020/06/Icons8_Logo.png',
    },
    {
        name: 'Iconscout',
        categories: [assets.icons],
        description:
            'Pixel-perfect vector icons and Icon Fonts available in Line, Monochrome, and Solid style for your next project.',
        url: 'https://iconscout.com/unicons',
        icon: 'https://iconscout.com/favicon-96x96.png',
    },
    {
        name: 'Iconshock',
        categories: [assets.icons],
        description:
            'Free icons and premium icon packs.  Flat icons, Material icons, Glyph icons, iOS icons, Font icons, and more design styles. Vector files, including PNG and SVG icons. Ready for apps, web or social media projects.',
        keywords: [
            'web icons',
            'web icon set',
            'web icon',
            'professional icons',
            'software  web icons',
            'web icons vista',
            'xp web icons',
            'windows vista icons',
            'windows icons',
            'vector icons',
            'vector web icons',
            'application icons',
            'java web icons',
            'video icons',
            'business icons',
            'multimedia icons',
            'accounting icons',
            'web icon packs',
            'web icone',
        ],
        url: 'https://www.iconshock.com/',
        icon: 'https://www.iconshock.com/img/favicon.ico',
    },
    {
        name: 'IconSweets',
        categories: [assets.icons],
        description:
            'IconSweets is a huge set containing over 1,000 custom designed icons. IconSweets 2 will quench your icon thirst for all your iPhone, iPad & Android apps or new web projects.',
        url: 'https://www.designbombs.com/iconsweets2/',
        icon: 'https://www.designbombs.com/iconsweets2/favicon-96x96.png',
    },
    {
        name: 'Icônes',
        categories: [assets.icons],
        description: 'Icon Explorer with Instant searching, powered by Iconify',
        url: 'https://icones.netlify.app/',
        icon: 'https://icones.netlify.app/favicon.svg',
    },
    {
        name: 'Image Optimizer',
        categories: [assets.images],
        description: 'Compress and resize photos.',
        url: 'http://www.imageoptimizer.net/',
        icon: 'data:image/x-icon;,',
    },
    {
        name: 'Inclusive Components',
        categories: [toolsAndUtilities.accessibility],
        description:
            'A blog trying to be a pattern library. All about designing inclusive web interfaces, piece by piece.',
        url: 'https://inclusive-components.design/',
        icon: 'https://inclusive-components.design/favicon.ico',
    },
    {
        name: 'Indeed',
        categories: [jobs.resumeBuilders],
        description: 'Build and upload your resume to Indeed and let your next job find you.',
        url: 'https://www.indeed.com/create-resume',
        icon: 'https://www.indeed.com/profile/gatsby-assets/icons/icon-96x96.png?v=d69338e3b43810840b9a84d69dbaa30e',
    },
    {
        name: 'Indie Bits',
        categories: [indieHacking.podcasts],
        description:
            "Short, bite-sized conversations (15 mins) with indie hackers that have started small, profitable and bootstrapped businesses. You'll learn how they come up with ideas, what they do to validate, find those first customers and make a sustainable income.",
        url: 'https://indiebites.co/',
        icon: 'https://s3.amazonaws.com/super-notion/images/26707ca1-dc44-44e8-90ce-9e6220840f71.png',
    },
    {
        name: 'Indie Hackers',
        categories: [indieHacking.platforms, indieHacking.podcasts],
        description:
            'Connect with developers who are sharing the strategies and revenue numbers behind their companies and side projects.',
        url: 'https://www.indiehackers.com/',
        icon: 'https://www.indiehackers.com/images/favicons/favicon--32x32.png',
    },
    {
        name: 'Indie Worldwide',
        categories: [indieHacking.platforms],
        description: 'The worldwide virtual meetup of indie hackers, founders, and makers.',
        url: 'https://indieworldwide.co/',
        icon: 'https://indieworldwide.co/icons/icon-96x96.png',
    },
    {
        name: 'Insomnia',
        categories: [toolsAndUtilities.apiBuilding],
        description: 'Design & Debug APIs like a human, not a robot.',
        url: 'https://insomnia.rest/',
        icon: 'https://insomnia.rest/icons/icon-96x96.png?v=b68a1a35ee1565b759a2d4edb26074be',
    },
    {
        name: 'IntelliJ IDEA',
        categories: [toolsAndUtilities.editorsAndExtensions],
        description: 'A Capable and Ergonomic Java IDE for Enterprise Java, Scala, Kotlin and much more...',
        url: 'https://www.jetbrains.com/idea/',
        icon: 'https://www.jetbrains.com/favicon-32x32.png',
    },
    {
        name: 'Interfacer',
        categories: [assets.illustrations],
        description: 'Interfacer is a collection of 300+ free design resources found on the Web.',
        keywords: [
            'design resources',
            'web design',
            'freedesignresources',
            'free design resources',
            'fonts',
            'free illustration',
            'freebies',
            'freebie illustration',
            'UI kits',
            'design kit',
            'Illustrations',
            'free fonts',
            'free Illustrations',
            'free mockups',
            'free icons',
            'Interfacer',
            'Interfacer list',
            'Interfacer design resource',
            'Interfacer resources',
            'Interfacer design resources',
        ],
        url: 'https://interfacer.xyz/',
        icon: 'https://interfacer.xyz/assets/site_assets/interfacelogo-icon.png',
    },
    {
        name: 'IntersectionObserver Examples',
        description: 'Practical, real world React examples of Intersection Observer',
        categories: [
            programming.codeSnippets,
            programming.docsAndCheatsheets,
            programming.javascript.react,
            programming.learn,
        ],
        keywords: [
            'IntersectionObserver',
            'IntersectionObserver API',
            'IntersectionObserver examples',
            'React',
            'React IntersectionObserver',
        ],
        url: 'https://intersectionobserver.io',
        icon: 'https://intersectionobserver.io/favicon.png',
    },
    {
        name: 'iOS Dev Jobs',
        categories: [jobs.boards],
        description:
            'Browse the very best iOS development jobs available, or sign up and get a weekly digest delivered by email every Monday.',
        url: 'https://iosdevjobs.com/',
        icon: 'https://iosdevjobs.com/wp-content/uploads/2019/01/cropped-favicon-32x32.png',
    },
    {
        name: 'IRA Design',
        categories: [assets.illustrations],
        description: 'Open-source illustrations that fits perfectly for any project you desire.',
        keywords: [
            'illustration',
            'app',
            'website illustration',
            'app illustration',
            'design component',
            'custom illustration',
            'illustration component',
            'color gradient',
            'gradients',
            'gallery',
            'best illustrations',
            'colorful illustrations',
        ],
        url: 'https://iradesign.io/gallery/illustrations',
        icon: 'https://iradesign.io/assets/img/favicon.png',
    },
    {
        name: 'Isometriclove',
        description: 'Cute isometric objects for your design.',
        categories: [assets.illustrations],
        url: 'https://isometriclove.com/',
        icon: 'https://isometriclove.com/favicon.ico',
    },
    {
        name: 'Illustrations-figma',
        description:
            'More than 5000 vector illustrations you can use inside Figma. All the figma illustrations are in SVG & PNG formats and includes styles like flat, lined, abstract and more.',
        categories: [assets.illustrations],
        url: 'https://www.artify.co/illustrations-figma',
        icon: 'https://www.artify.co/images/landing/favicon.png',
    },
    {
        name: 'Iconshock',
        description:
            'The biggest icon pack with over 2 million professional icons in +400 icon sets with more than 30 design styles: material, flat, 3d, realistic, iOS, and more.',
        categories: [assets.icons],
        url: 'https://www.iconshock.com/',
        icon: 'https://www.iconshock.com/img/favicon.ico',
    },
]
