name: Update DB and README

on:
    push: { branches: main }
    # schedule:
    #     # Every day at 00:00AM
    #     - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    update-db-and-readme:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm install
            - run: npm run update-db
            - run: npm run update-readme
            - run: npm run prettier:format
            - run: git add .
            - run: git commit -m "Auto updating db and README.md" || echo "Nothing to commit"
            - run: git push origin HEAD:main
